#! /bin/bash

_vmrun()
{
  local current previous options
  COMPREPLY=()
  current="${COMP_WORDS[COMP_CWORD]}"
  previous="${COMP_WORDS[COMP_CWORD-1]}"
  #  The basic options we'll complete.
  options="start stop"

  #
  #  Complete the arguments to some of the basic commands.
  #
  case "${previous}" in
    start)
      local names=$(for x in `ls -1 $HOME/Documents/Virtual_Machines.localized/*/*.vmx`; do echo ${x/$HOME\/Documents\/Virtual_Machines.localized\//} ; done );
      COMPREPLY=( $(compgen -W "${names}" -- ${current}) )
      return 0
      ;;
    stop)
      local names=$(for x in `ls -1 $HOME/Documents/Virtual_Machines.localized/*/*.vmx`; do echo ${x/$HOME\/Documents\/Virtual_Machines.localized\//} ; done );
      COMPREPLY=( $(compgen -W "${names}" -- ${current}) )
      return 0
      ;;
    *)
      COMPREPLY=( $(compgen -W "${options}" -- ${current}) )
      return 0
      ;;
  esac

}
complete -F _vmrun vmrun
